### ISSUE TITLE
Seemingly Breaks as Required Field

### ISSUE THREAD

**Issue by smallbizwhiz** [soderlind/date-range-ninja-forms#5]
First--LOVE the plugin. It's exactly what I needed as a novice and really surprised NF didn't already have this built-in. Thank you for building AND for sharing!!

I noticed when building the form and having the picker as a required field, two things happen:

1. The first time I pick a date range, while it accepts the range and inputs it in the field, the field still appears as though it did not, according to the validation. If I select the same or different dates a second time, it works.

2. That is until I attempt to submit the form, at which point it says the field doesn't contain the required data.
![2020-04-02_0226](https://user-images.githubusercontent.com/62855454/78309862-2fd04800-751a-11ea-81f7-98e9efef29a2.png)
![2020-04-02_0225_001](https://user-images.githubusercontent.com/62855454/78309864-3068de80-751a-11ea-8b7d-07a6dcb90d75.png)
![2020-04-02_0225](https://user-images.githubusercontent.com/62855454/78309865-3068de80-751a-11ea-99b4-941aa826dbd9.png)

**Comment by soderlind** [comment]
fixed in latest release
